[package]
name = "s3_upload"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.92"
aws-config = "1.5.9"
aws-sdk-dynamodb = "1.52.0"
aws-sdk-s3 = "1.59.0"
futures = "0.3.31"
tokio = { version = "1.41.0", features = ["full"] }
